### ISSUE TITLE
Target first level <li> by using LESS nested rules with BEM

### ISSUE THREAD

**Issue by thehung2224** [bem-site/bem-method#191]
I have the following HTML:

``` html
<ul class="header-menu">
    <li class="header-menu__item"><a href="index.html">home</a></li>
    <li class="header-menu__item header-menu__item--split"><a href="menu.html">menu</a></li>
    <li class="header-menu__item">
        <a href="#">features</a>
        <ul class="header-menu--dropdown">
            <li><a href="menu.html">Menu</a></li>
        </ul>
    </li>
</ul>    <!-- end header-menu -->
```

I have this css, is it possible to do something like this in less:

``` css
.header-menu{}
    .header-menu .header-menu__item{}
    .header-menu > .header-menu__item{}
```

I would write it in LESS with BEM like this: 

``` css
.header-menu{
    &__item{
        display: inline-block;
        float: left;
    }

    > &__item{ // How can I target first <li>(s) here
    }
}
```

How can I apply a CSS rule to the first `<li>` level? Tried `> &__item` but it doesn't seem to work.
