### ISSUE TITLE
Ошибка в приложенном коде

### ISSUE THREAD

**Issue by pawwvw** [bem-site/bem-method#878]
https://ru.bem.info/methodology/css/#dry

В разделе описывается принцип DRY в БЭМ.

### **Как неправильный представлен код:**

HTML
```html
<button class="button">...</button>
<button class="btn">...</button>
```

CSS
```css
.button {
    font-family: Arial, sans-serif;
    text-align: center;
    color: #000;
    background: #fff;
}

.btn {
    font-family: Arial, sans-serif;
    text-align: center;
    color: #000;
    background: rgba(255, 0, 0, 0.4);
}
```

![image](https://github.com/user-attachments/assets/57fae8d4-98be-4a19-904e-afce7ca973e4)

### **А как правильный:**

HTML
```html
<button class="button button_theme_islands">...</button>
<button class="button button_theme_simple">...</button>
```

CSS
```css
.button {
    font-family: Arial, sans-serif;
    text-align: center;
}

.button_theme_islands {
    color: #000;
    background: #fff;
}

.button_theme_simple {
    color: #000;
    background: rgba(255, 0, 0, 0.4);
}
```

![image](https://github.com/user-attachments/assets/d89a3d97-6251-48f9-9a53-fce9d80eb481)

Что, кажется, не совсем соответствует принципам DRY

Возможно вы имели ввиду:

 CSS
```css
.button {
    font-family: Arial, sans-serif;
    text-align: center;
    color: #000;
}

.button_theme_islands {
    background: #fff;
}

.button_theme_simple {
    background: rgba(255, 0, 0, 0.4);
}
```
